# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Closeme < Formula
  desc "Fun little TUI where you try to close the box"
  homepage "https://github.com/ansipixels"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ansipixels/closeme/releases/download/v1.0.0/closeme_1.0.0_darwin_amd64.zip"
      sha256 "72e8e33313013859b3fb9ac70acbacdd78392436d02c892176800aeb2082f701"

      define_method(:install) do
        bin.install "closeme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ansipixels/closeme/releases/download/v1.0.0/closeme_1.0.0_darwin_arm64.zip"
      sha256 "fc37702a7764cff6e2f506b60bfe0622cd63b6d62b8e48e182ea4618873b4ab4"

      define_method(:install) do
        bin.install "closeme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ansipixels/closeme/releases/download/v1.0.0/closeme_1.0.0_linux_amd64.tar.gz"
      sha256 "16c56b083a6bf3037323cb663f3e33b2fea031fff405b04d2578cc98b77b6ed5"
      define_method(:install) do
        bin.install "closeme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ansipixels/closeme/releases/download/v1.0.0/closeme_1.0.0_linux_arm64.tar.gz"
      sha256 "01bbcd8475e54ac2f0d80b20dd6db1e821ba1436d43299005872d31a02769642"
      define_method(:install) do
        bin.install "closeme"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/closeme -version")
  end
end
