# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Closeme < Formula
  desc "Fun little TUI where you try to close the box"
  homepage "https://github.com/ansipixels"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ansipixels/closeme/releases/download/v1.1.0/closeme_1.1.0_darwin_amd64.zip"
      sha256 "ec6f83ea7683102643327cf755a9f7c8508c5df95fc7d95bfbbce19b3250b4b2"

      define_method(:install) do
        bin.install "closeme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ansipixels/closeme/releases/download/v1.1.0/closeme_1.1.0_darwin_arm64.zip"
      sha256 "c77ea22490cff0ccf1f4e03194bd4905a9ae34f3e3622e3238ca0e9cab6ed487"

      define_method(:install) do
        bin.install "closeme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ansipixels/closeme/releases/download/v1.1.0/closeme_1.1.0_linux_amd64.tar.gz"
      sha256 "01bf82b286fc6795130428ed779ff6941488d22da52e4a64a83d8983b86f4b83"
      define_method(:install) do
        bin.install "closeme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ansipixels/closeme/releases/download/v1.1.0/closeme_1.1.0_linux_arm64.tar.gz"
      sha256 "4839e80e171f00bb57135037ba2e5e04bdc4b5807eeff0a254ae0c927f9cab85"
      define_method(:install) do
        bin.install "closeme"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/closeme -version")
  end
end
