# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trophy < Formula
  desc "Terminal 3D Model Viewer - View 3D model files in your terminal - ansipixels port"
  homepage "https://github.com/ansipixels"
  version "1.5.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ansipixels/trophy/releases/download/v1.5.4/trophy_1.5.4_darwin_amd64.zip"
      sha256 "12e4a102172403aa3da4e46c89846834d04f64e98be6e1b7a0783fb7271d89f6"

      def install
        bin.install "trophy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ansipixels/trophy/releases/download/v1.5.4/trophy_1.5.4_darwin_arm64.zip"
      sha256 "644c378e7a9489ee28c2b76f40dcf5adac0b00a08f0b8d9d893256caf3f6a22f"

      def install
        bin.install "trophy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ansipixels/trophy/releases/download/v1.5.4/trophy_1.5.4_linux_amd64.tar.gz"
      sha256 "10a9401bb7ae3e187d94cb7623e3f72b1886d47159c2dbb176ba9dffa5e27819"
      def install
        bin.install "trophy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ansipixels/trophy/releases/download/v1.5.4/trophy_1.5.4_linux_arm64.tar.gz"
      sha256 "e3a5aa7a9a99181e64637de53dbff0fd962d1c7088cdb878406e3797cfee206c"
      def install
        bin.install "trophy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/trophy -version")
  end
end
